### ISSUE TITLE
Failed to open session: client_id_unavailable

### ISSUE THREAD

**Issue by rjbaat** [emqx/emqx-auth-http#86] opened 2018-10-18 18:09 UTC
Because the config page of the plugin is empty in EMQX 3.0 Beta 4.
Or will it accept the config ENV in docker?

**Comment by rjbaat** [comment] 2018-10-19 07:35
I tested with the right ENV in docker. And the plugin is loaded and most of the time it works. It does the Post to the webhook.  But one of the 3 nodes are giving the error: 
Failed to open session: client_id_unavailable.
while the exact same connections are made on all 3 nodes.

**Comment by rjbaat** [comment] 2018-10-19 07:43
Btw this is happening with both GET and POST calls and seems random on one of the 3 nodes.

**Comment by Gilbert-Wong** [comment] 2018-10-27 06:08
This error means that the session has been locked. Maybe you use the same clientid to connect emq cluster at the same time.

**Comment by rjbaat** [comment] 2018-11-02 12:09
Well i connect behind HAproxy, but with dynamic client ID. Maybe with reconnecting the connection is redirected to a different node. Is there some setting or timeout i have to set so the client id is cleared faster?

**Comment by rjbaat** [comment] 2018-11-12 13:13
I tried locally with 3 node cluster of 3.0 RC3. 
I made 3 connections with all 3 different client id's. 

connect worker 1 -> node 1
connect worker 2 -> node 2
connect worker 3 -> node 3

All 3 connections subscribe to topic: $share/group_1/test with clean session true.

Atm 2 connections are made successfully but one is not

```
(emq3@emq3.mq.tt)1> EMQ X Broker 3.0-rc.3 is running now!

(emq3@emq3.mq.tt)1> 2018-11-12 13:09:59.413 [error] mqtt_794713a1.48bb7c@10.255.0.2:34720 [MQTT] Failed to open session: client_id_unavailable

(emq3@emq3.mq.tt)1> 2018-11-12 13:10:14.447 [error] mqtt_794713a1.48bb7c@10.255.0.2:34770 [MQTT] Failed to open session: client_id_unavailable

(emq3@emq3.mq.tt)1> 2018-11-12 13:10:29.438 [error] mqtt_794713a1.48bb7c@10.255.0.2:34818 [MQTT] Failed to open session: client_id_unavailable

(emq3@emq3.mq.tt)1> 2018-11-12 13:10:44.433 [error] mqtt_794713a1.48bb7c@10.255.0.2:34898 [MQTT] Failed to open session: client_id_unavailable

(emq3@emq3.mq.tt)1> 2018-11-12 13:10:59.446 [error] mqtt_794713a1.48bb7c@10.255.0.2:34946 [MQTT] Failed to open session: client_id_unavailable

(emq3@emq3.mq.tt)1> 2018-11-12 13:11:14.426 [error] mqtt_794713a1.48bb7c@10.255.0.2:35000 [MQTT] Failed to open session: client_id_unavailable

```
So this is done without HAproxy.

**Comment by rjbaat** [comment] 2019-01-11 14:38
Tried on the latest emqx 3.0.
With only 1 node. But this problem still occurs.
I setup a http request with GET.
But i still get the message:
[MQTT] Failed to open session: client_id_unavailable
[MQTT] Process packet error - einval

**Comment by Gilbert-Wong** [comment] 2019-01-30 02:06
If there is just one emqx node, this problem could not be triggered, the error message `client_id_unavailable` would only be triggered in cluster mode of emqx.

**Comment by GerogeLeon** [comment] 2019-05-06 08:52
i encountered this problem too, but what is the effect of it

**Comment by HJianBo** [comment] 2020-04-07 09:20
Sorry guys, I will close it due to it is outdated.

If somebody reproduced it, Plz opens a new issue. Thanks

**Closed by HJianBo** 2020-04-07 09:20 UTC
Labels: support
