### ISSUE TITLE
Topic name comes in strange when implementing the API - switching it's param position shifts the issue

### ISSUE THREAD

**Issue by a3aanwisse** [emqx/emqx-auth-http#57] opened 2017-12-20 15:44 UTC
Referring to issue #38 which is closed. In my opinion it still is an issue. See my latest comment on that issue.

When shifting the parameter position of topic to another position the last referred parameter will have this issue

And when adding `,unused=unused` as last parameter you can also _fix_ the issue. Since the other data will come in correctly and you just ignore this parameter.

**Comment by emqplus** [comment] 2017-12-26 01:59
@a3aanwisse The issue is fixed in PR: https://github.com/emqtt/emq-relx/pull/152

**Closed** 2019-04-24 16:03 UTC
Labels: bug
