### ISSUE TITLE
401 status still let the client to connect

### ISSUE THREAD

**Issue by wudaoren** [emqx/emqx-auth-http#160] opened 2019-09-26 14:13 UTC
#### Environment
 - OS: CentOS-7
 - EMQ: v3.2.3

#### Description
 I am returning 401.but the client is still able to connect.

error log:
```
2019-09-26 17:56:27.748 [warning] sdfxvcvxc@139.205.94.115:20698 [Protocol] Client sdfxvcvxc (Username: 'wang') login failed for 401
2019-09-26 17:56:42.046 [warning] sdfxvcvxcsdfsdf@139.205.94.115:20707 [Protocol] Client sdfxvcvxcsdfsdf (Username: 'wang') login failed for 401
```

**Comment by turtleDeng** [comment] 2019-09-26 14:43
The issue is already at https://github.com/emqx/emqx/issues/2939, I will close this issue

**Closed by turtleDeng** 2019-09-26 14:43 UTC
